### ISSUE TITLE
Refactoring required

### ISSUE THREAD

**Issue by oleksiigu** [bigroko/java-lessons#1]
- For collection declaration you need to use interface instead of implementation:
List<Cell> cells = new ArrayList<>();
- better use next project stracture:
http://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
- methods should be lowerCamelCase, Start() should be renamed
- better to use MessageFormat instead of concat
- Complex logic in Board.java constructor, logic of constructor shouldn't be complex:
http://misko.hevery.com/code-reviewers-guide/flaw-constructor-does-real-work/

**Comment by bigroko** [comment]
Done.
